/* =========================================================
   MODULE: AUTH & CORE USERS
   ========================================================= */

-- Tabla de Usuarios (Credenciales y Roles básicos)
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL, -- 300 es excesivo para BCrypt, 255 sobra
    name VARCHAR(100) NOT NULL, -- Necesario para emails transaccionales
    role VARCHAR(50) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de Refresh Tokens (Para sesión persistente en móvil)
CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token VARCHAR(255) NOT NULL UNIQUE,
    expiry_date TIMESTAMP NOT NULL,
    CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Tabla de Tokens de Confirmación (Registro por email)
CREATE TABLE confirmation_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    confirmed_at TIMESTAMP,
    confirmed BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_conf_token_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Tabla de Reseteo de Password
CREATE TABLE reset_passwords (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    code VARCHAR(10) NOT NULL, -- 6 dígitos suele bastar
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_reset_pass_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

/* =========================================================
   MODULE: USER PROFILE (Desacoplado de Auth)
   ========================================================= */

CREATE TABLE user_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE, -- 1 a 1 lógico, pero desacoplado
    name VARCHAR(100),
    surname VARCHAR(100),
    contact_email VARCHAR(100),
    about_me TEXT, -- TEXT en Postgres es ilimitado y performante
    city VARCHAR(100),
    birthday DATE,
    zipcode VARCHAR(10),
    phone_number VARCHAR(20),
    photo TEXT, -- Best Practice: Guardar URL (S3/Cloudinary), no el BLOB en DB
    job_title VARCHAR(100),
    education VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Nota: No Foreign Key estricta si queremos microservicios reales en futuro,
    -- pero para Monolito Modular ayuda a la integridad:
    CONSTRAINT fk_profile_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

/* =========================================================
   MODULE: CAREER (Experiences)
   ========================================================= */

CREATE TABLE experiences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    company_name VARCHAR(250) NOT NULL,
    department VARCHAR(250),
    position VARCHAR(250) NOT NULL,
    start_date DATE NOT NULL,
    finish_date DATE,
    functions TEXT, -- TEXT en Postgres es ilimitado y performante
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_experience_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

/* =========================================================
   MODULE: FEEDBACK (Cache Requests - Tu lógica de negocio)
   ========================================================= */

-- Petición de Feedback/Cache
CREATE TABLE cache_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    experience_id BIGINT NOT NULL,
    relationship_id INT NOT NULL, -- Podría ser un Enum o tabla aparte
    still_works_there BOOLEAN NOT NULL,
    target_name VARCHAR(100) NOT NULL,
    target_surname VARCHAR(100) NOT NULL,
    target_email VARCHAR(100) NOT NULL,
    url_token VARCHAR(100) NOT NULL, -- URL única para contestar
    finished BOOLEAN NOT NULL DEFAULT FALSE,
    target_phone VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_request_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_request_experience FOREIGN KEY (experience_id) REFERENCES experiences(id) ON DELETE CASCADE
);

-- Respuesta de Feedback (Requested Cache)
CREATE TABLE requested_caches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT, -- Quién recibe el feedback
    experience_id BIGINT,
    cache_request_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- Métricas (Normalizadas a snake_case)
    flexibility FLOAT,
    integrity FLOAT,
    proactivity FLOAT,
    self_confidence FLOAT, -- Antes selfconfidence
    teamwork FLOAT,

    -- Respuestas detalladas (JSONB es ideal en Postgres para formularios dinámicos,
    -- pero mantengo columnas planas por ahora para respetar tu legacy)
    question1 INT,
    question2 INT,
    question3 INT,
    question4 VARCHAR(255),
    question5 VARCHAR(255),
    question6 INT,

    CONSTRAINT fk_rc_request FOREIGN KEY (cache_request_id) REFERENCES cache_requests(id) ON DELETE SET NULL
);

/* =========================================================
   MODULE: ANALYTICS / STATS
   ========================================================= */

CREATE TABLE user_skills_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    teamwork FLOAT DEFAULT 0,
    self_confidence FLOAT DEFAULT 0,
    proactivity FLOAT DEFAULT 0,
    integrity FLOAT DEFAULT 0,
    flexibility FLOAT DEFAULT 0,
    average_score FLOAT DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_metrics_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);